---
switches:
  hosts:
    spine-1:
      name: "spine-1"
      ansible_httpapi_port: 8001
      # ansible_host: linux-netmanager.tradezero.co
      ansible_host: azure-linux-networkmanager.tradezero.co
    spine-2:
      name: "spine-2"
      ansible_httpapi_port: 8002
      # ansible_host: linux-netmanager.tradezero.co
      ansible_host: azure-linux-networkmanager.tradezero.co
    leaf-1:
      name: "leaf-1"
      ansible_httpapi_port: 8003
      # ansible_host: linux-netmanager.tradezero.co
      ansible_host: azure-linux-networkmanager.tradezero.co
    leaf-2:
      name: "leaf-2"
      ansible_httpapi_port: 8004
      # ansible_host: linux-netmanager.tradezero.co
      ansible_host: azure-linux-networkmanager.tradezero.co
    leaf-3:
      name: "leaf-3"
      ansible_httpapi_port: 8005
      # ansible_host: linux-netmanager.tradezero.co
      ansible_host: azure-linux-networkmanager.tradezero.co
    rtr-1:
      name: "rtr-1"
      ansible_httpapi_port: 8006
      ansible_host: azure-linux-networkmanager.tradezero.co
