---
- hosts: localhost
  vars:
  tasks: 

  - name: add "{{ switch_name }}" to inventory
    add_host:
      name: "{{ switch_name }}"
      ansible_connection: httpapi
      ansible_host: localhost
      ansible_port: "{{ port_number }}"
      ansible_user: admin
      ansible_password: "password1!"
      ansible_network_os: eos
      ansible_httpapi_use_ssl: True
      ansible_command_timeout: 30
      ansible_host_key_checking: False
    changed_when: false

  - name: load configuration from file
    delegate_to: "{{ switch_name }}"
    eos_config:
      src: configs/{{ switch_name }}_portchannel.ios