---
- hosts: localhost
  vars:
  tasks: 

  - name: add "{{ switch_name }}" to inventory
    add_host:
      name: "{{ switch_name }}"
      ansible_connection: httpapi
      ansible_host: localhost
      ansible_httpapi_port: "{{ port_number }}"
      ansible_user: admin
      ansible_password: "password1!"
      ansible_network_os: eos
      ansible_command_timeout: 30
      ansible_host_key_checking: False
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_become: True
    changed_when: false

  - name: save running-config
    delegate_to: "{{ switch_name }}"
    eos_config:
      backup: yes
      backup_options:
        dir_path: configs
        filename: "{{ switch_name }}_running-config.cfg"